apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: blackboxes.blackbox.monitoring.com
spec:
  group: blackbox.monitoring.com
  names:
    kind: Blackbox
    listKind: BlackboxList
    plural: blackboxes
    singular: blackbox
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
